<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kandidat_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			kandidat.id as id,
			kandidat.nama as nama,
			kandidat.SOFTSKILL as SOFTSKILL,
			kandidat.HARDSKILL as HARDSKILL,
			kandidat.PARAMETER_QUALITY as PARAMETER_QUALITY,
			kandidat.ROLEPLAY as ROLEPLAY,
			kandidat.KEHADIRAN as KEHADIRAN,
			kandidat.status as status,
			kandidat.kelulusan as kelulusan,
		');
		
		$this->datatables->from('kandidat');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'kandidat.id as id',
			'kandidat.nama as nama',
			'kandidat.SOFTSKILL as SOFTSKILL',
			'kandidat.HARDSKILL as HARDSKILL',
			'kandidat.PARAMETER_QUALITY as PARAMETER_QUALITY',
			'kandidat.ROLEPLAY as ROLEPLAY',
			'kandidat.KEHADIRAN as KEHADIRAN',
			'kandidat.status as status',
			'kandidat.kelulusan as kelulusan',
		
		);
		$this->db->select($afield);

		$this->db->order_by('kandidat.id', 'ASC');
		return $this->db->get('kandidat')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'kandidat.id as id',
			'kandidat.nama as nama',
			'kandidat.SOFTSKILL as SOFTSKILL',
			'kandidat.HARDSKILL as HARDSKILL',
			'kandidat.PARAMETER_QUALITY as PARAMETER_QUALITY',
			'kandidat.ROLEPLAY as ROLEPLAY',
			'kandidat.KEHADIRAN as KEHADIRAN',
			'kandidat.status as status',
			'kandidat.kelulusan as kelulusan',
		
		);
		$this->db->select($afield);

		$this->db->where('kandidat.id', $id);
		$this->db->order_by('kandidat.id', 'ASC');
		return $this->db->get('kandidat')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('kandidat.id <>',$id);

		$q = $this->db->get_where('kandidat', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('kandidat', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('kandidat.id', $id);
		$this->db->update('kandidat', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('kandidat.id',$data);	
	
			$this->db->delete('kandidat');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-11-29 15:30:34 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
