<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kandidat_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->kandidat_id	= 'ID';
		$this->kandidat_nama	= 'NAMA';
		$this->kandidat_SOFTSKILL	= 'SOFTSKILL';
		$this->kandidat_HARDSKILL	= 'HARDSKILL';
		$this->kandidat_PARAMETER_QUALITY	= 'PARAMETER_QUALITY';
		$this->kandidat_ROLEPLAY	= 'ROLEPLAY';
		$this->kandidat_KEHADIRAN	= 'KEHADIRAN';
		$this->kandidat_status	= 'STATUS';
		$this->kandidat_kelulusan	= 'KELULUSAN';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nama	= 'nama';
		$this->f_SOFTSKILL	= 'SOFTSKILL';
		$this->f_HARDSKILL	= 'HARDSKILL';
		$this->f_PARAMETER_QUALITY	= 'PARAMETER_QUALITY';
		$this->f_ROLEPLAY	= 'ROLEPLAY';
		$this->f_KEHADIRAN	= 'KEHADIRAN';
		$this->f_status	= 'status';
		$this->f_kelulusan	= 'kelulusan';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->kandidat_id,
			$this->f_nama	=> $this->kandidat_nama,
			$this->f_SOFTSKILL	=> $this->kandidat_SOFTSKILL,
			$this->f_HARDSKILL	=> $this->kandidat_HARDSKILL,
			$this->f_PARAMETER_QUALITY	=> $this->kandidat_PARAMETER_QUALITY,
			$this->f_ROLEPLAY	=> $this->kandidat_ROLEPLAY,
			$this->f_KEHADIRAN	=> $this->kandidat_KEHADIRAN,
			$this->f_status	=> $this->kandidat_status,
			$this->f_kelulusan	=> $this->kandidat_kelulusan,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-11-29 15:30:34 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

