<?php
require APPPATH . '/controllers/Approve/Approve_config.php';

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Approve extends CI_Controller
{
	private $log_key, $log_temp, $title;
	function __construct()
	{
		parent::__construct();
		$this->load->model('ContentManagementModel');
		$this->load->model('Custom_model/Sys_user_table_model', 'Sys_user_table_model');
		$this->load->model('sys/Sys_user_log_model', 'log_login');
		$this->load->model('Custom_model/Dapros_model', 'Dapros');
		$this->log_key = 'log_Indibox';
		$this->title = new Approve_config();
	}


	public function index()
	{


		$data = array(
			'title_page_big'		=> 'Approval Content & Campaign',
			'title'					=> $this->title,
		);
		$data['controller'] = $this;
		$data['list'] = $this->db->query("SELECT * FROM trx_campaign ")->result_array();


		$this->template->load('Approve/Approve_list', $data);
	}
	public function save()
	{
		$idlogin = $this->session->userdata('idlogin');
		$logindata = $this->log_login->get_by_id($idlogin);
		$data['userdata'] = $this->Sys_user_table_model->get_row(array("id" => $logindata->id_user));
		$datetime = NOW();
		$data = array(
			'date_approve' => $datetime,
			'status_approve' => $_POST['status_approve'],
			'feedback' => $_POST['feedback'],
			'approve_by' => $logindata->id_user
		);
		$this->db->set($data);
		$this->db->where('id', $_POST['id']);
		$this->db->update('trx_campaign');
		redirect('/Approve/Approve', 'refresh');
	}
	public function edit($id)
	{
		$data = array(
			'title_page_big'		=> 'Approval Content & Campaign',
			'title'					=> $this->title,
			'link_update'			=> site_url() . 'Approve/Approve/update_action/' . $id
		);
		$data['data'] = $this->db->query("SELECT * FROM trx_campaign WHERE id='$id'")->row();
		$data['landing_page'] = $this->db->query("SELECT * FROM dim_landingpage");
		$data['area'] = $this->db->query("SELECT * FROM dim_regional")->result();
		$data['nama_produk'] = $this->db->query("SELECT * FROM dim_produk");
		$this->template->load('Approve/Edit_form', $data);
	}
	public function preview($id)
	{
		$data = array(
			'title_page_big'		=> 'Preview Content & Campaign',
			'title'					=> $this->title,
			'link_update'			=> site_url() . 'Approve/Approve/update_action/' . $id
		);
		$data['data'] = $this->db->query("SELECT * FROM trx_campaign WHERE id='$id'")->row();
		$konten_email = $data['data']->email_content;
		// $email_image = $campaign->email_image;
		$konten_wa = $data['data']->wa_des;
		$konten_sms = $data['data']->sms_desc;

		$link_lp = $this->get_lplink();
		$data['email_image_name'] = $data['data']->email_image;
		$data['email_image'] = "https://sy-anida.com/image_public/" . $data['email_image_name'];
		$data['wa_image'] = $data['data']->wa_image;
		$data['wa_video'] = $data['data']->wa_video;
		$data['link_lp'] = $link_lp;
		$data['type_content_wa'] = $data['data']->type_content_wa;
		$data['email'] = str_replace("{link}", $link_lp, $konten_email);
		$data['wa'] = str_replace("{link}", $link_lp, $konten_wa);
		$data['sms'] = str_replace("{link}", $link_lp, $konten_sms);

		$this->load->view('Approve/preview', $data);
	}
	public function get_lplink($no_internet = '11', $no_hp = '11', $produk = 'ESSENTIAL')
	{
		// if ($id) {
		$curl = curl_init();
		$url = "https://subsystem.indihome.co.id/dashboard-ultra/api/insertAddon";
		$arr = array(
			"noinet" => $no_internet,
			"msisdn" => $no_hp,
			"produk" => $produk,
			"source" => 'DSI',
			"type" => 'minipack'
		);
		$data = http_build_query($arr);

		curl_setopt_array($curl, array(
			CURLOPT_URL => $url,
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_ENCODING => "",
			CURLOPT_MAXREDIRS => 10,
			CURLOPT_TIMEOUT => 0,
			CURLOPT_FOLLOWLOCATION => true,
			CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			CURLOPT_CUSTOMREQUEST => "POST",
			CURLOPT_POSTFIELDS => $data,
			CURLOPT_HTTPHEADER => array(
				"Content-Type: application/x-www-form-urlencoded"
			),
		));

		$response = curl_exec($curl);
		$response = json_decode($response);
		if (isset($response->data->link)) {
			return $response->data->link;
		}
	}
	public function refresh_table($token)
	{
		if ($token == $this->_token) {
			$row = $this->tmodel->json();

			//encode id 
			$tm = time();
			$this->session->set_userdata($this->log_key, $tm);
			$x = 0;
			foreach ($row['data'] as $val) {
				$idgenerate = _encode_id($val['id'], $tm);
				$row['data'][$x]['id'] = $idgenerate;
				$x++;
			}

			$o = new Outputview();
			$o->success	= 'true';
			$o->serverside	= 'true';
			$o->message	= $row;

			echo $o->result();
		} else {
			redirect('Auth');
		}
	}
};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-06-02 15:25:04 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
